### ISSUE TITLE
feature: search cards for exact text contained in the oc_file_path 

### ISSUE THREAD

**Issue by kmkhami** [arguflow/ai-editor#129]
We can use Postgres' `LIKE` filter for this

https://qdrant.tech/documentation/concepts/filtering/#has-id

**Comment by kmkhami** [comment]
Steps for accomplishing this PR: 

DB Migration to add a [trigram_index with gist](https://www.cybertec-postgresql.com/en/postgresql-more-performance-for-like-and-ilike-statements/) on the `oc_file_path` column . [Here is a guide on doing that with diesel ](https://diesel.rs/guides/getting-started#cb6). 

1. Modify the `SearchCardData` struct to include a `filter_oc_file_path` key 
2. Modify `search_card_query` to take the `filter_oc_file_path` path param 
3. Modify `search_card_query` to first make a postgres query to the db to get a `Vector<uuid::Uuid>` of all the `qdrant_point_id`'s of `card_metadata` rows that are filtered by `LIKE` on the `oc_file_path` with the `filter_oc_file_path` 
4. Change the Qdrant query to use [has-id](https://qdrant.tech/documentation/concepts/filtering/#has-id) with the vec of  the `qdrant_point_id`'s that are returned by step 3 

Then it should all work and you just need to wire it into the frontend

**Comment by kmkhami** [comment]
Relevant Qdrant docs: 

https://docs.rs/qdrant-client/latest/qdrant_client/qdrant/struct.Filter.html
https://docs.rs/qdrant-client/latest/qdrant_client/qdrant/struct.SearchPoints.html

**Comment by densumesh** [comment]
- [ ] DB Migration to add a [trigram_index with gist](https://www.cybertec-postgresql.com/en/postgresql-more-performance-for-like-and-ilike-statements/) on the oc_file_path column
- [ ] Modify the SearchCardData struct to include a filter_oc_file_path key
- [ ] Modify search_card_query to take the filter_oc_file_path path param
- [ ] Modify search_card_query to first make a postgres query to the db to get a Vector<uuid::Uuid> of all the qdrant_point_id's of card_metadata rows that are filtered by LIKE on the oc_file_path with the filter_oc_file_path
- [ ] Change the Qdrant query to use [has-id](https://qdrant.tech/documentation/concepts/filtering/#has-id) with the vec of the qdrant_point_id's that are returned by step 3
